replicaCount: 1

image:
  repository: ghaitho20/pcd_backend
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

resources: {}

namespace: backend

env:
  DB_HOST: "postgres-db-postgresql.backend.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "centregreffeDB"
  DB_USER: "postgres"
  DB_PASSWORD_SECRET_NAME: postgres-db-postgresql
  DB_PASSWORD_SECRET_KEY: postgres-password
  


