replicaCount: 1

image:
  repository: ghaitho20/pcd_backend
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

resources: {}

namespace: backend

env:
  - name: DB_HOST
    value: "postgres-db-postgresql.db.svc.cluster.local"
  - name: DB_PORT
    value: "5432"
  - name: DB_NAME
    value: "pcd_db"
  - name: DB_USER
    value: "pcd_user"
  - name: DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: postgres-db-postgresql
        key: password
